### ISSUE TITLE
Setup wizard - with plugins

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-e2e-tests#3]
This setup step turns out to be very brittle in e2e environment - plugins (and themes) are frequently not being installed. 

E.g. one error that surfaced was this (during jetpack plugin installation):
```
[17-Mar-2020 16:44:28 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/newspack-plugin-ZbCMw1/includes/wizards/class-setup-wizard.php on line 221
[17-Mar-2020 16:46:28 UTC] PHP Warning:  dir(/var/www/html/wp-content/upgrade/jetpack.8.3-JMCGbg/jetpack/_inc/build/photon/): failed to open dir: No such file or directory in /var/www/html/wp-admin/includes/class-wp-filesystem-direct.php on line 571
[17-Mar-2020 16:46:29 UTC] PHP Warning:  dir(/var/www/html/wp-content/upgrade/jetpack.8.3-JMCGbg/jetpack/modules/custom-css/custom-css/css/rtl/): failed to open dir: No such file or directory in /var/www/html/wp-admin/includes/class-wp-filesystem-direct.php on line 571
```

Another time, the AMP plugin did seem to install, but possibly not completely, and threw this error (on the front-end):
```
Warning: include(/var/www/html/wp-content/plugins/amp/vendor/composer/../sabberworm/php-css-parser/lib/Sabberworm/CSS/Parsing/ParserState.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/amp/vendor/composer/ClassLoader.php on line 444 Warning: include(): Failed opening '/var/www/html/wp-content/plugins/amp/vendor/composer/../sabberworm/php-css-parser/lib/Sabberworm/CSS/Parsing/ParserState.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/amp/vendor/composer/ClassLoader.php on line 444 Fatal error: Uncaught Error: Class 'Sabberworm\CSS\Parsing\ParserState' not found in /var/www/html/wp-content/plugins/amp/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php:26 Stack trace: #0 /var/www/html/wp-content/plugins/amp/includes/sanitizers/class-amp-style-sanitizer.php(1599): Sabberworm\CSS\Parser->__construct('img.wp-smiley,\n...', Object(Sabberworm\CSS\Settings)) #1 /var/www/html/wp-content/plugins/amp/includes/sanitizers/class-amp-style-sanitizer.php(1685): AMP_Style_Sanitizer->parse_stylesheet('img.wp-smiley,\n...', Array) #2 /var/www/html/wp-content/plugins/amp/includes/sanitizers/class-amp-style-sanitizer.php(1435): AMP_Style_Sanitizer->prepare_stylesheet('img.wp-smiley,\n...', Array) #3 /var/www/html/wp-content/plugins/amp/includes/sanitizers/class-amp-style-sanitizer.php(1193): AMP_Style_Sanitizer->process_stylesheet('img.wp-smiley,\n...', Array) #4 /var/www/html/wp-content/plugins/amp/includes/sanitizers/class-amp-style-sanitizer.php(853): AMP_Style_Sanitizer->process_style_element(Object(DOM in /var/www/html/wp-content/plugins/amp/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php on line 26
```

In one case, the theme did not _fully_ download (or rather extract) - `header.php` was missing in the theme folder.

**Comment by adekbadek** [comment]
For now the plugins are pre-installed.
